services:
  client_web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - EXPOSE_PORT_SERVER=8080
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./services/router
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - server-tier
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  csharp_service:
    build:
      context: ./services/advanced
      dockerfile: Dockerfile
    depends_on:
      server:
        condition: service_healthy
    networks:
      - server-tier
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  oauth_service:
    build:
      context: ./services/oauth
      dockerfile: Dockerfile
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - DROPBOX_CLIENT_ID=${DROPBOX_CLIENT_ID}
      - DROPBOX_CLIENT_SECRET=${DROPBOX_CLIENT_SECRET}
    depends_on:
      server:
        condition: service_healthy
    networks:
      - server-tier
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  service-about:
    build:
      context: ./services/about
      dockerfile: Dockerfile
    depends_on:
      server:
        condition: service_healthy
    networks:
      - server-tier
    volumes:
      - services-storage:/var/service_storage
      - ./lib/serviceconf:/usr/src/app/serviceconf
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/about.json"]
      interval: 10s
      timeout: 5s
      retries: 5

  service-action:
    build:
      context: ./services/action
      dockerfile: Dockerfile
    depends_on:
      csharp_service:
        condition: service_healthy
    networks:
      - server-tier
    volumes:
      - services-storage:/var/service_storage
      - ./lib/protocol:/usr/src/app/protocol
      - ./lib/serviceconf:/usr/src/app/serviceconf
      - ./lib/service_mod:/usr/src/app/service_mod

  service-reaction:
    build:
      context: ./services/reaction
      dockerfile: Dockerfile
    depends_on:
      csharp_service:
        condition: service_healthy
    networks:
      - server-tier
    volumes:
      - services-storage:/var/service_storage
      - ./lib/protocol:/usr/src/app/protocol
      - ./lib/serviceconf:/usr/src/app/serviceconf
      - ./lib/service_mod:/usr/src/app/service_mod

  db:
    image: "postgres:15"
    networks:
      - server-tier
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

  docs:
    build:
      context: ./area-doc
      dockerfile: Dockerfile
    ports:
      - "8082:8080"

  swagger-doc:
    build:
      context: ./services/swagger
      dockerfile: Dockerfile
    networks:
      - server-tier
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/swagger"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  server-tier:

volumes:
  postgres-data:

  services-storage:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'data/service_storage'
