routes:
  - name: auth-login
    host: csharp_service
    port: 8080
    condition: ^/auth/login$


  - name: auth-register
    host: csharp_service
    port: 8080
    condition: ^/auth/register$

  - name: area
    host: csharp_service
    port: 8080
    condition: ^/area$

  - name: get-services
    host: csharp_service
    port: 8080
    condition: ^/area/([^/]+)/services$

  - name: subscribe-service
    host: csharp_service
    port: 8080
    condition: ^/area/([^/]+)/subscribe_service$
  
  - name: actions-reactions
    host: csharp_service
    port: 8080
    condition: ^/area/([^/]+)/services/([^/]+)/actions_reactions$

  - name: action
    host: csharp_service
    port: 8080
    condition: ^/area/([^/]+)/services/([^/]+)/action$

  - name: reaction
    host: csharp_service
    port: 8080
    condition: ^/area/([^/]+)/services/([^/]+)/reaction$

  - name: about
    host: service-about
    port: 80
    condition: ^/about.json$

  # Add new routes here







  ###------------------ Swagger ------------------###

  - name: swagger-doc
    host: swagger-doc
    port: 3000
    condition: ^/swagger/$

  - name: swagger-ui-css
    host: swagger-doc
    port: 3000
    condition: ^/swagger/swagger-ui.css$

  - name: swagger-ui-bundle-js
    host: swagger-doc
    port: 3000
    condition: ^/swagger/swagger-ui-bundle.js$

  - name: swagger-ui-standalone-preset-js
    host: swagger-doc
    port: 3000
    condition: ^/swagger/swagger-ui-standalone-preset.js$

  - name: swagger-ui-init-js
    host: swagger-doc
    port: 3000
    condition: ^/swagger/swagger-ui-init.js$
