routes:
  - name: auth-login
    host: csharp_service
    port: 8080
    condition: ^/auth/login$

  - name: auth-register
    host: csharp_service
    port: 8080
    condition: ^/auth/register$
  
  - name: area
    host: csharp_service
    port: 8080
    condition: ^/area$