routes:
  - name: auth-login
    host: csharp_service
    port: 8080
    condition: ^/auth/login$

  - name: auth-register
    host: csharp_service
    port: 8080
    condition: ^/auth/register$

  - name: about
    host: service-about
    port: 80
    condition: ^/about.json$