# docker-compose to run the frontend vueJS app using Dockerfile in the same folder of this file,
# then a backend server located in ../../../Backend/rust_router_test/ from this file.

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - server-tier

  backend:
    image: rust_router_test
    build:
      context: ../../../Backend/rust_router_test/
    ports:
      - "8000:8000"
    networks:
      - server-tier
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "postgres:latest"
    networks:
      - server-tier
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure



networks:
  server-tier:

volumes:
  postgres_data:
