name: AWS Deployment

on: workflow_dispatch
  # push:
  #   branches:
  #     - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install docker compose
        run: sudo apt-get install docker-compose

      - name: Set up ssh private key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/area-serv.pem
          chmod 400 ~/.ssh/area-serv.pem

      - name: Deploy to AWS
        run: |
          ssh -i "~/.ssh/area-serv.pem" -o "StrictHostKeyChecking no" admin@ec2-15-188-14-84.eu-west-3.compute.amazonaws.com << EOF
            cd /home/admin/A.R.E.A/
            git fetch
            git switch main
            git pull --force
            sudo docker-compose up -d
          EOF
